version: '2.1'
orbs:
  docker: circleci/docker@2.1.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          executor:
            image: circleci/node
            name: docker/docker
            tag: boron-browsers
          image: my/image
          remote-docker-dlc: true
          tag: my-tag
          use-remote-docker: true
